-- SCRIPTS TABELAS RESERVJA --

CREATE TABLE `apartamento` (
  `ID_APARTAMENTO` int NOT NULL AUTO_INCREMENT,
  `NUM_QUARTO` int DEFAULT NULL,
  `QTD_OCUPANTES` int DEFAULT NULL,
  `STATUS_APARTAMENTO` enum('DISPONIVEL','OCUPADO','RESERVADO') DEFAULT NULL,
  PRIMARY KEY (`ID_APARTAMENTO`),
  UNIQUE KEY (`NUM_QUARTO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `CLIENTE` (
 `ID_CLIENTE` int NOT NULL AUTO_INCREMENT,
 `NOME` varchar(255) DEFAULT NULL,
 `SOBRENOME` varchar(255) DEFAULT NULL,
 `EMAIL` varchar(255) DEFAULT NULL,
 `SEXO` varchar(255) DEFAULT NULL,
 `DATA_NASCIMENTO` date DEFAULT NULL,
 `ENDERECO` int DEFAULT NULL,
 PRIMARY KEY (`ID_CLIENTE`),
  KEY (`ENDERECO`),
  CONSTRAINT FOREIGN KEY (`ENDERECO`) REFERENCES `endereco` (`ID_ENDERECO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `endereco` (
  `ID_ENDERECO` int NOT NULL AUTO_INCREMENT,
  `CEP` varchar(255) DEFAULT NULL,
  `LOGRADOURO` varchar(255) DEFAULT NULL,
  `BAIRRO` varchar(255) DEFAULT NULL,
  `COMPLEMENTO` varchar(255) DEFAULT NULL,
  `MUNICIPIO` varchar(255) DEFAULT NULL,
  `UF` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_ENDERECO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `funcionario` (
  `ID_FUNC` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) DEFAULT NULL,
  `SOBRENOME` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `DATA_NASCIMENTO` date DEFAULT NULL,
  `USUARIO` varchar(255) DEFAULT NULL,
  `SENHA` varchar(255) DEFAULT NULL,
  `ENDERECO` int DEFAULT NULL,
  PRIMARY KEY (`ID_FUNC`),
  UNIQUE KEY (`USUARIO`),
  KEY (`ENDERECO`),
  CONSTRAINT FOREIGN KEY (`ENDERECO`) REFERENCES `endereco` (`ID_ENDERECO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

